spring.application.name=PlayMySongs
# Define o tamanho máximo de um único arquivo (ex: 10MB)
spring.servlet.multipart.max-file-size=10MB
# Define o tamanho máximo da requisição total (ex: 10MB)
spring.servlet.multipart.max-request-size=10MB